### ISSUE TITLE
子view少的时候 滑动会崩溃

### ISSUE THREAD

**Issue by xiaoyuaidalu** [baiduapp-tec/ELinkageScroll#4]

**Comment by YouthLee** [comment]
老铁，崩溃日志看看呢

**Comment by xiaoyuaidalu** [comment]
2020-03-23 15:18:44.621 29855-29855/com.baidu.elinkagescroll E/AndroidRuntime: FATAL EXCEPTION: main
&nbsp; &nbsp; Process: com.baidu.elinkagescroll, PID: 29855
&nbsp; &nbsp; java.lang.NullPointerException: Attempt to invoke interface method 'com.baidu.elinkagescroll.LinkageScrollHandler com.baidu.elinkagescroll.ILinkageScroll.provideScrollHandler()' on a null object reference
&nbsp; &nbsp; &nbsp; &nbsp; at com.baidu.elinkagescroll.ELinkageScrollLayout.getLinkageScrollHandler(ELinkageScrollLayout.java:608)
&nbsp; &nbsp; &nbsp; &nbsp; at com.baidu.elinkagescroll.ELinkageScrollLayout.scrollTo(ELinkageScrollLayout.java:425)
&nbsp; &nbsp; &nbsp; &nbsp; at com.baidu.elinkagescroll.ELinkageScrollLayout.computeScroll(ELinkageScrollLayout.java:364)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.View.updateDisplayListIfDirty(View.java:20454)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4397)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4370)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.View.updateDisplayListIfDirty(View.java:20431)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4397)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4370)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.View.updateDisplayListIfDirty(View.java:20431)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4397)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4370)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.View.updateDisplayListIfDirty(View.java:20431)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4397)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4370)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.View.updateDisplayListIfDirty(View.java:20431)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4397)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4370)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.View.updateDisplayListIfDirty(View.java:20431)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4397)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4370)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.View.updateDisplayListIfDirty(View.java:20431)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:580)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:586)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:659)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.ViewRootImpl.draw(ViewRootImpl.java:3871)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3671)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2993)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1930)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8018)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1163)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.Choreographer.doCallbacks(Choreographer.java:986)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.Choreographer.doFrame(Choreographer.java:902)
&nbsp; &nbsp; &nbsp; &nbsp; at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1148)
&nbsp; &nbsp; &nbsp; &nbsp; at android.os.Handler.handleCallback(Handler.java:883)
&nbsp; &nbsp; &nbsp; &nbsp; at android.os.Handler.dispatchMessage(Handler.java:100)
&nbsp; &nbsp; &nbsp; &nbsp; at android.os.Looper.loop(Looper.java:214)
&nbsp; &nbsp; &nbsp; &nbsp; at android.app.ActivityThread.main(ActivityThread.java:7682)
&nbsp; &nbsp; &nbsp; &nbsp; at java.lang.reflect.Method.invoke(Native Method)
&nbsp; &nbsp; &nbsp; &nbsp; at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
&nbsp; &nbsp; &nbsp; &nbsp; at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)






你可以把你的demo除了第二个view 全部去掉 来回划几下 就会崩溃
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"YouthLee"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月23日(星期一) 下午3:14
收件人:&nbsp;"MFC-TEC/ELinkageScroll"<ELinkageScroll@noreply.github.com&gt;;
抄送:&nbsp;"大萌璐"<99554768@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MFC-TEC/ELinkageScroll] 子view少的时候 滑动会崩溃 (#4)





 
老铁，崩溃日志看看呢

**Comment by 371280835** [comment]
有两个子控件且两个控件的高度不足以撑满整个屏幕的时候，滑动就会崩溃了，我这里也会。
