### ISSUE TITLE
当子view RecyclerView的数据更新变少后，滑动会崩溃

### ISSUE THREAD

**Issue by Aidenat9** [baiduapp-tec/ELinkageScroll#9]
recyclerview的布局被包裹
`<com.youtoo.baidu.scroll.view.LFrameLayout
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content">
                        <android.support.v7.widget.RecyclerView
                            android:id="@+id/rv"
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"
                            android:paddingLeft="7.5dp"
                            android:paddingRight="7.5dp" />
                    </com.youtoo.baidu.scroll.view.LFrameLayout>`

错误：
`UncaughtException detected: java.lang.NullPointerException: Attempt to invoke interface method 'com.youtoo.baidu.scroll.LinkageScrollHandler com.youtoo.baidu.scroll.ILinkageScroll.provideScrollHandler()' on a null object reference
        at com.youtoo.baidu.scroll.ELinkageScrollLayout.getLinkageScrollHandler(ELinkageScrollLayout.java:608)
        at com.youtoo.baidu.scroll.ELinkageScrollLayout.scrollTo(ELinkageScrollLayout.java:425)
        at com.youtoo.baidu.scroll.ELinkageScrollLayout.computeScroll(ELinkageScrollLayout.java:364)
        at android.view.View.updateDisplayListIfDirty(View.java:18056)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
        at android.view.View.updateDisplayListIfDirty(View.java:18032)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
        at android.view.View.updateDisplayListIfDirty(View.java:18032)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
        at android.view.View.updateDisplayListIfDirty(View.java:18032)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
        at android.view.View.updateDisplayListIfDirty(View.java:18032)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
        at android.view.View.updateDisplayListIfDirty(View.java:18032)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
        at android.view.View.updateDisplayListIfDirty(View.java:18032)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
        at android.view.View.updateDisplayListIfDirty(View.java:18032)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
        at android.view.View.updateDisplayListIfDirty(View.java:18032)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
        at android.view.View.updateDisplayListIfDirty(View.java:18032)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
        at android.view.View.updateDisplayListIfDirty(View.java:18032)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
        at android.view.View.updateDisplayListIfDirty(View.java:18032)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4198)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4178)
        at android.view.View.updateDisplayListIfDirty(View.java:18032)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:643)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:649)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:757)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3003)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2807)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2360)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1399)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6788)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
        at android.view.Choreographer.doCallbacks(Choreographer.java:778)
        at android.view.Choreographer.doFrame(Choreographer.java:713)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
        at android.os.Handler.handleCallback(Handler.java:789)
    	at android.os.Handler.d`

**Comment by CWTakiku** [comment]
同上

**Comment by huangxinbao** [comment]
修改下源码可以继续跑，ELinkageScrollLayout类中的scrollTo()方法更改一处 （430行）  View target = getTargetByEdge(edge);增加判断    if (target != null)  在继续执行可以暂时解决一楼的问题；

**Comment by huangxinbao** [comment]
修改下源码可以继续跑，ELinkageScrollLayout类中的scrollTo()方法更改一处 （430行左右） View target = getTargetByEdge(edge);增加判断 if (target != null) 在继续执行可以暂时解决一楼的问题；

**Comment by Aidenat9** [comment]
确实，这个问题是咱们的recyclerview的数据变化后高度变化，而elinkageScrollLayout有一个记录位置和高度的集合，只再初始化时添加了数据，view高度变化时他没有更新相应高度，导致View target = getTargetByEdge(edge);获取到的target为空。【望作者修复】

**Comment by huangxinbao** [comment]
> ew的数据变化后高度变化，而elinkageScrollLayout有一个记录位置和高度的集合，只再初始化时添加了数据，view高度变化时他没有更新相应高度，导致View target = getTargetByEdge(edge);获取到的target为空。【望作者修复】

布局有变化会调用onLayout重新布局，这个没有问题；获取到的target为空其实是逻辑处理的问题：
getNextEdge() 获取返回值的问题（有next正常返回，没有next返回0 或者“容器最大可滑动距离”），如果手指下滑获取的为0, getTargetByEdge() 方法可以获取到第一个view； 而如果手指上滑，可能获取“容器最大可滑动距离”；这个距离不一定有view的topEdge,会和这个相等；所以返回target为空，只有在下一步加个判断就可以； 当然如果最后一个view是高度math_parent ; 上面的问题都不存在
